subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 14
      leftSlaveOne: 13
      rightMain: 1
      rightSlaveOne: 2
    victors:
      rightSlaveTwo: 0
      leftSlaveTwo: 15
  climber:
    implemented: true
    talons:
      climbMaster: 3
      climbSlave: 12
    doubleSolenoids:
      habPiston:
        forward: 5
        reverse: 6
  cargocollector:
    implemented: true
    talons:
      intake: 11
    solenoids:
      arm: 2
  birdbeak:
    implemented: true
    solenoids:
      beak: 1
      puncher: 3
  cargoshooter:
    implemented: true
    talons:
      arm: 5
      intake: 10
    constants:
      kP: 2.5
      kI: 0
      kD: 1.0
      kF: 0
      maxPos: 3690
      midPos: 2800
      minPos: 2425
  ledmanager:
    implemented: true
    canifier: 18
pcm: 17
constants:
  wheelbase: 25
  ticksPerRev: 1025
  ticksPerIn: 50
  maxVel: 800
  cheezyDrive: 0
  loggingEnabled: 1
